version: '3.9'

services:
  cep-api:
    image: wiremock/wiremock:2.32.0
    container_name: cep-api
    volumes:
      - ./local-setup:/home/wiremock
    ports:
      - 8383:8080

  mongo-db:
    image: mongo:4.2.6
    restart: always
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: mongo-express_container
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo-db
